//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_mgt_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_details
    {
        public int userID { get; set; }
        public Nullable<int> loginID { get; set; }
        public Nullable<int> userTypeID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Contact { get; set; }
        public string email { get; set; }
    
        public virtual tbl_login tbl_login { get; set; }
        public virtual tbl_userType tbl_userType { get; set; }
    }
}
