//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_mgt_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_login()
        {
            this.tbl_user_details = new HashSet<tbl_user_details>();
        }
    
        public int login_id { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public Nullable<bool> isApproved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_user_details> tbl_user_details { get; set; }
    }
}
